// Code generated by "tsdoc-testify"; DO NOT EDIT.

import * as assert from "assert";
import { sub } from "./sub";
test("/Users/silverbirder/github.com/silverbirder/playground/node/doctest-sample-app/src/sub.ts_0", () => {
  assert.equal(sub(2, 1), 1);
});
test("/Users/silverbirder/github.com/silverbirder/playground/node/doctest-sample-app/src/sub.ts_1", () => {
  assert.equal(sub(4, 5), -1);
});
